# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe17ea179ae1702ab9818b7c1e5e76e81acf4354499b77bd0bac685de3b4c3308bf7b994295aff7f959f319fda8ddac740e54fcb2354e4db342854d11ada7bb0

test:
  secret_key_base: 31494f4f7ae686ddec8c830d3eda41829e277dd0ea466c63971fc5af1286802df4773b23f63734e6bf6f8513590d84bc108e09a9f78cde3b1a63ec24b0d20513

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
